### ISSUE TITLE
Interceptors?

### ISSUE THREAD

**Issue by bdcarr** [googleapis/gaxios#181]
Hey friends, I found this module via https://github.com/JustinBeckwith/retry-axios/issues/1, and tried it out as a 'drop-in replacement' for axios because I need that sweet retry goodness and `retry-axios` has this issue where it only retries once, then seems to...forget my config. Something seems to be missing, though: interceptors!

**Is your feature request related to a problem? Please describe.**
I think this is a feature request, unless I'm _really bad_ at reading documentation. Couldn't see an indication in the source code that it's supported either.

So I copy/paste replaced `axios` with `gaxios`, ran my code...

```javascript
const requests = require('gaxios'),
  _ = require('lodash')

const logHttpErrorDetails = requests.interceptors.response.use(/* my fully sick function for logging all error responses */)
```

...and got this error:
```TypeError: Cannot read property 'response' of undefined```

 **Describe the solution you'd like**
I would like axios-like interceptors supported for use in `gaxios`.

 **Describe alternatives you've considered**
Probably just going back to `axios` and putting up with my `retry-axios` issue.

 **Additional context**
🙏

**Comment by jhoch** [comment]
I am interested in instrumenting requests made with `gaxios`.  I saw [this issue](https://github.com/googleapis/gaxios/issues/36) where someone mentioned instrumentation, but it's not obvious to me how to do that trivially with `adapter`, since the "default adapter" relies on a few private methods, so wrapping it is difficult (`adapter` is still great for testing of course).  The better approach to instrumentation, to me, feels like interceptors

**Comment by bcoe** [comment]
@joseglego please don't hesitate to open a feature request.
