### ISSUE TITLE
What is gaxios?

### ISSUE THREAD

**Issue by avin-kavish** [googleapis/gaxios#243]
I'm confused. I was reading the Google OAuth2 workflow when I saw a link to this library. What is the advantage of using this over axios?

**Comment by bdcarr** [comment]
There are probably other things, but the one I know of is that gaxios has retry capabilities built-in. With axios, you'd have to use something like `retry-axios`.

**Comment by JustinBeckwith** [comment]
Greetings folks!  As it turns out, HTTP libraries are really nuanced things.  `axios` is lovely!  But we needed something that:
- Has built in support for retries
- Built in support for proxies
- Very light weight, with a fetch style under-layer

We mostly use this for our clients.  While you can use it as a general HTTP client, projects like axios or [got](https://github.com/sindresorhus/got) will have broader appeal, and larger communities.  

Hope this helps!

**Comment by avin-kavish** [comment]
I'm not sure about the lightweight claim, 

- https://bundlephobia.com/result?p=gaxios@3.0.2
- https://bundlephobia.com/result?p=axios@0.19.2
