### ISSUE TITLE
A comparrison between this and SuperAgent, Axios, GOT

### ISSUE THREAD

**Issue by tryhardest** [googleapis/gaxios#329]
This library looks great. We have compared the bundle sizes and dependency but in looking at Axios, SuperAgent and GOT it's hard to make a determination on why this one should be the stand out choice. They all look pretty similar but I am wondering if Gaxios is handling something they are not that I might've missed (or has added advantages ). Thanks.

**Comment by JustinBeckwith** [comment]
Greetings!  We wrote this library because we needed a stable, well understood request library that suited our specific needs.  Before this library, we used request.  We had to stop using that because it got huge, and then got deprecated.  We then moved to axios, which had (for a time) some serious bugs, and appeared to be unmaintained.  At the end of the day, we wanted to control exactly which features got in, and exactly what the interfaces look like.  This was really required so we could serve folks with Google's npm modules, without worrying about the ground shifting out from under us. 

The primary goal of this library is *not* to be a general purpose HTTP client that solves everyones needs.  We do think it's pretty useful, and matches what we wanted in terms of feature/performance/size tradeoffs.  

If you're looking for a well supported, general purpose HTTP client - I would actually recommend using `got` over this library.  `got` is good enough, has tons of users, and also supports many nice features.  Hope this helps!
