### ISSUE TITLE
Incorrectly adding '=' to url when query string has only a value (not a key and value)

### ISSUE THREAD

**Issue by drmrbrewer** [googleapis/gaxios#331]
Consider the following:

    const { request } = require('gaxios');
    try {
        const response = await request({ url: 'https://pae-paha.pacioos.hawaii.edu/erddap/griddap/ww3_global.json?Thgt%5B(2020-09-03T11%3A31%3A13Z)%3A1%3A(last)%5D%5B(0.0)%3A1%3A(0.0)%5D%5B(51.5)%3A1%3A(52.5)%5D%5B(354.5)%3A1%3A(355.5)%5D%2CTdir%5B(2020-09-03T11%3A31%3A13Z)%3A1%3A(last)%5D%5B(0.0)%3A1%3A(0.0)%5D%5B(51.5)%3A1%3A(52.5)%5D%5B(354.5)%3A1%3A(355.5)%5D' });
        console.log('response:', response);
    } catch (error) {
        console.log('error:', error);
    }

This results in an error because it looks like gaxios is parsing the url and converting what comes after `?` as a query string, but the query string here isn't of the form `key=val` but rather is just plain `val`.  So gaxios is effectively converting this into `val=` ...  i.e. adding an unwanted `=` at the end of the original url, and this is what is causing the error here.

Whilst it may be unusual to have a url of this form, surely gaxios should just accept it literally, or at least interpret it literally if the query string doesn't have a key/value.

**Comment by sofisl** [comment]
Hi @drmrbrewer, thanks for submitting. It sounds like you have a workaround by modifying the string? Let me know if it is completely blocked for you. Thanks!

**Comment by drmrbrewer** [comment]
Hi @sofisl ... I don't have a workaround (other than to revert to using request).  When I pass the correct url (without trailing `=`) it is always converted internally by gaxios into a url having a trailing `=`, which results in an error.  I can't see any way of stopping this from happening, because the url has to be in the form `...?val` rather than `...?key=val`... and this is always converted to `...?val=`.

**Comment by JustinBeckwith** [comment]
I took a close look at this one :) The issue here is that neither [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) nor [qs.parse](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) will return `undefined` for situations where an `=` isn't provided.  For example:

```
> qs.stringify({ foo: undefined })
'foo='
```

Querystring parsing is complicated, with many edge cases.  This is not the kind of thing I would want to implement in this library, and I don't think it's something we can support.  There is good news though!  You can totally inject your own querystring param serializer!  

```js
  // By default, we use the `querystring` package in node core to serialize
  // querystring parameters.  You can override that and provide your
  // own implementation.
  paramsSerializer: (params) => {
    return qs.stringify(params);
  },
```

Instead of `qs.stringify`, you could use this config option to create your own querystring.  If you know the situations where you're facing one of these URLs, you can decide exactly how it should be put back together :) 

Hope this helps!

**Comment by drmrbrewer** [comment]
Thanks, that's a workaround I can deal with.  But for me it is still surprising (and maybe to others) that the `url` is not just used verbatim, particularly if you are doing a super-simple GET request with just a `url` and no separate `params` passed in: `request({ url: "https://...?blah" })`.  My expectation (clearly incorrect in this case) would be that the `url` is used "as-is".  Instead, it seems to be subject to something like `qs.stringify(qs.parse(...))` to mash it up a little when you least expect it :)  Maybe I just need to re-align my expectations, because I'm a million miles away from being the expert here, and it my url has a non-standard query string then I have to expect a few bumps on the road... :)
