### ISSUE TITLE
Request failed with status code 302

### ISSUE THREAD

**Issue by fullflash** [googleapis/gaxios#366]
We are getting error 

```
Error: Request failed with status code 302
    at Gaxios._request (/Users/fersmart/Projects_all/Project_OnMaral/onmaral_api/node_modules/gaxios/build/src/gaxios.js:89:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
followAllRedirects is true .

Looks like gaxios not follow redirects.

```
let options = {
        url: url,
        timeout: 10000,
        method: "GET",
        // responseType: "json",
        responseType:"bloc",
        followAllRedirects: true,
        // responseType:"bloc",//_ALL getting timeout with asos request but json with ninewest
    };
```

**Comment by sofisl** [comment]
Hi @fullflash, can you provide a code snippet of what you are trying to execute, as well as any relevant environment details, including versions, etc.?

**Comment by fullflash** [comment]
here is the url  you can test with simple curl.
https://www.macys.com/shop/product/michael-michael-kors-skyler-sneaker?ID=4587098&CategoryID=55760

with postman without any additional headers i get response 200.

**Comment by fullflash** [comment]
it works when testing with simple browser.
on first get request server returns 302 redirect with "set-cookie" parameters look like need to forward original url with cookies headers.

**Comment by sofisl** [comment]
@fullflash, we support redirects, but we don't support cookies. We are not planning on supporting cookies because gaxios is designed for interacting with simple JSON apis.

If you're looking for support with cookies, you might want to use [axios](https://github.com/axios/axios) and [axios-cookiejar-support](https://www.npmjs.com/package/axios-cookiejar-support).
