### ISSUE TITLE
Do you have a plant to update node-fetch to v3？

### ISSUE THREAD

**Issue by yumetodo** [googleapis/gaxios#445]
Already, renovate-bot create #426 to introduce node-fetch v3 and it was rejected.

I'm interested in https://github.com/node-fetch/node-fetch/issues/667 and it is fixed in node-fetch v3.

Do you have a plant to update node-fetch to v3？

**Comment by dobromyslov** [comment]
@chingor13 node 10 has been dropped already. Here is the official timeline https://github.com/nodejs/Release

And I agree it's not trivial because it requires all packages depending on the node-fetch 3 to be migrated from CommonJS to ESM.

Why don't you just make a new gaxios v3 beta branch and release it with ESM support to kick off the migration?

**Comment by yumetodo** [comment]
> migrated from CommonJS to ESM.

That is exactly what I missed when I create this issue. creating a beta branch looks good to me.

**Comment by dobromyslov** [comment]
@yumetodo herr is a workaround I use:
1. Migrate your own project to the ESM.
2. Import gaxios 2.x. ESM allows import CommonJS modules. 
3. Default import node-fetch 3.1 which is ESM already. 
4. Set **GaxiosOptions fetchImplementation** to the imported fetch.
5. Run your gaxios request with the custom fetchImplementation.
6. If you need to set custom node-fetch options just set them to the GaxiosOptions object. And they will be passed to the fetch request under the hood.
