### ISSUE TITLE
formdata gets stringified

### ISSUE THREAD

**Issue by simllll** [googleapis/gaxios#447]
#### Environment details

  - OS: linux
  - Node.js version: v16.10
  - npm version: 7.24.1
  - `gaxios` version: 4.3.2

#### Steps to reproduce

send a form dat areuqest
```ts
const formData = new FormData();
formData.append('test', 123);

gaxios.request({method: POST, data: formData;})
```

The request is stringiefied because of this line here https://github.com/googleapis/gaxios/blob/cc3dd894a9102692e389e7a7d529ac9898074ef4/src/gaxios.ts#L247

formdata is typeof object.

a possible fix will be to check if object is a formdata first and in this case don't touch it?
e.g.
```
  else if (typeof FormData !== 'undefined' && opts.data instanceof FormData) {
// remove content-type header...  
} else if (typeof opts.data === 'object') { ...
```

altenative would be to allow skipping the whole transformation step in the validate step.. e.g. via flag?

**Comment by tyayers** [comment]
I think this is also causing problems for me when trying to post form binary data to the Apigee API to deploy proxies (zip files), makes sense that it doesn't work if all form data is stringified..

Here's my code:
`         
const form = new FormData();
var newFile = fs.readFileSync(bundlePath);
form.append('file', newFile, `${proxyName + ".zip"}`);

client.request({
  url: `https://apigee.googleapis.com/v1/organizations/${projectId}/apis?name=${proxyName}&action=import`,
  method: "post",
  headers: {
    ...form.getHeaders()
  },
  data: form
}).then((response) => {
  let proxyRevision: ProxyRevision = response.data as ProxyRevision;
  resolve(proxyRevision);
}).catch((error) => {
  reject(error);
});`

And the error:
     Error: invalid multipart/form-data encoding: failed to read multipart body part: multipart: NextPart: bufio: buffer full
      at Gaxios._request (node_modules/gaxios/src/gaxios.ts:158:15)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async JWT.requestAsync (node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)

Works fine with axios, so switched back to that for now.

**Comment by sofisl** [comment]
Hi @simllll, I have a PR open to fix this issue. One thing I'm not sure about is that you mention that data is stringified because of [this line](https://github.com/googleapis/gaxios/blob/cc3dd894a9102692e389e7a7d529ac9898074ef4/src/gaxios.ts#L259), but that actually stringifies the body. Did you mean to say that the body gets stringified, which you want fixed? Just to confirm, I've added an assertion here [that confirms we do nothing to the body](https://github.com/googleapis/gaxios/pull/475/files#diff-ebcc0b89f32624a5cb3272bf796d6ef05e5b08ae5557f026d586fcc474b990e8R398), which is what I'm assuming you're looking for. LMK if that looks right to you.

**Comment by sofisl** [comment]
I'm going to merge since this issue has gone OOSLO. Feel free to reopen if we need to make any other changes.
