### ISSUE TITLE
Support proxy option instead of HTTP_PROXY env variable

### ISSUE THREAD

**Issue by vamcc** [googleapis/gaxios#520]
**Is your feature request related to a problem? Please describe.**
Using `HTTP_PROXY` env variable will affect other requests which may also come from some other third-party packages. And not every package support `NO_PROXY` env variable. In my scene, I just want to proxy request from googleapis which depend on gaxios and keep other requests called directly.
 **Describe the solution you'd like**
Support `proxy` variable in options instead of global env variable, so that developers can keep the proxy in control.
``` javascript
gaxios.request({
  url: 'xxx',
  proxy: 'yyy'
})
```
 **Describe alternatives you've considered**
I tried to list all the third-party url and use `NO_PROXY` to resolve this problem, but I failed. Not every package support `NO_PROXY`
 **Additional context**

**Comment by bcoe** [comment]
@vamcc this library should be supporting `NO_PROXY`, could you provide a minimal example that is failing for you?

**Comment by vamcc** [comment]
> @vamcc this library should be supporting `NO_PROXY`, could you provide a minimal example that is failing for you?

Yes, but not every package use `gaxios` as its request client. Maybe some other request clients just support 'HTTP_PROXY’ but not 'NO_PROXY'. 
Actually，I tried to resolve this problem with options.agent yesterday and it looked work well.  
``` typescript
{
  agent: new HttpsProxyAgent(proxy),
}
```
I found that `proxy` from `HTTP_PROXY` will finally set to `opts.agent`. Here is the [source code](https://github.com/googleapis/gaxios/blob/main/src/gaxios.ts#L281).
I doubt is this an alternative provided for developers?😂

**Comment by drmrbrewer** [comment]
I agree that it would be nice to be able to specify a `proxy` on a per-request level via a simple `proxy: 'http://my.proxy.com'` option, rather than using a global env var [as suggested here](https://github.com/googleapis/gaxios/issues/378#issuecomment-813618369), which will apply to all requests made in that environment.

Having said that, it does indeed seem to be possible already to set a per-request proxy using `agent: new HttpsProxyAgent('http://my.proxy.com')` but this requires the extra leg-work of installing the [`https-proxy-agent` module](https://www.npmjs.com/package/https-proxy-agent) and importing with `import HttpsProxyAgent from 'https-proxy-agent'`... not a massive deal but a `proxy` option would be nicer IMHO!

**Comment by danielbankhead** [comment]
Resolving the shortly via:
- https://github.com/googleapis/gaxios/pull/614
